[project]
name = "plastax"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "jax>=0.4.0",
    "equinox>=0.11.0",
    "jaxtyping>=0.2.0",
]


[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
